export const CATEGORY_ICONS: Record<string, string> = {
  comida: 'Utensils',
  transporte: 'Bus',
  renta: 'Home',
  suscripciones: 'Tv',
  mercado: 'ShoppingCart',
  ocio: 'Sparkles',
  salario: 'Banknote',
  inversion: 'TrendingUp',
  recompensa: 'Award',
  regalos: 'Gift',
  negocio: 'Briefcase',
  ingreso: 'HandCoins',
  servicios: 'Lightbulb',
  deuda: 'CreditCard',
  default: 'Tag',
};
